# 開發階段
FROM golang:1.21

WORKDIR /app

# 複製 go.mod
COPY go.mod ./

# 下載依賴並生成 go.sum
RUN go mod download
RUN go get github.com/gin-gonic/gin@v1.9.1
RUN go get github.com/google/uuid@v1.6.0
RUN go mod tidy

# 複製源代碼
COPY . .

CMD ["go", "run", "cmd/main.go"]
