name: order-management-system
version: '3.8'

services:
  # API Gateway
  api-gateway:
    build: ../../api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - order-service
      - product-service
      - payment-service
      - notification-service

  # Auth Service
  auth-service:
    build: ../../auth-service
    environment:
      - DB_HOST=postgres-auth
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=auth_db
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    depends_on:
      - postgres-auth
      - redis

  # Order Service
  order-service:
    build: ../../order-service
    environment:
      - DB_HOST=postgres-order
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=order_db
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    depends_on:
      - postgres-order
      - redis

  # Product Service
  product-service:
    build: ../../product-service
    environment:
      - DB_HOST=postgres-product
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=product_db
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    depends_on:
      - postgres-product
      - redis

  # Payment Service
  payment-service:
    build: ../../payment-service
    environment:
      - DB_HOST=postgres-payment
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=payment_db
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    depends_on:
      - postgres-payment
      - redis

  # Notification Service
  notification-service:
    build: ../../notification-service
    environment:
      - DB_HOST=postgres-notification
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=notification_db
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    depends_on:
      - postgres-notification
      - redis

  # PostgreSQL Databases
  postgres-auth:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    ports:
      - "5437:5432"

  postgres-order:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order_db
    volumes:
      - postgres_order_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  postgres-product:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product_db
    volumes:
      - postgres_product_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  postgres-payment:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payment_db
    volumes:
      - postgres_payment_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  postgres-notification:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notification_db
    volumes:
      - postgres_notification_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Prometheus (監控)
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # Grafana (監控面板)
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  postgres_auth_data:
  postgres_order_data:
  postgres_product_data:
  postgres_payment_data:
  postgres_notification_data:
  redis_data:
