global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:8080"]

  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:8081"]

  - job_name: "order-service"
    static_configs:
      - targets: ["order-service:8083"]

  - job_name: "product-service"
    static_configs:
      - targets: ["product-service:8084"]

  - job_name: "payment-service"
    static_configs:
      - targets: ["payment-service:8085"]

  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:8086"]
